services:
  spotdl-ytm-service:
    pull_policy: build
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
    container_name: spotdl-ytm-service
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "blastbeng/spotdl-ytm-service:1.0.0"
    restart: unless-stopped
    ports:
      - 5484:5484
    volumes:
      - ".env:/app/.env"
      - "./config/config.json:/home/ytmuser/.spotdl/config.json"
      - "./config:/app/config"
      - "./logs:/app/logs"
      - "/var/media/musica:/var/media/musica"
    networks:
      spotdl-ytm-network:
        ipv4_address: 10.5.0.5
  spotdl-ytm-squid:
    image: ubuntu/squid:latest
    container_name: spotdl-ytm-squid
    ports:
      - "127.0.0.1:3128:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf
    restart: unless-stopped
    networks:
      spotdl-ytm-network:
        ipv4_address: 10.5.0.6


networks:
  spotdl-ytm-network:
    driver: bridge
    enable_ipv6: true
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1